stages:
  - set_up_infrastructure
  - build_image
  - deploy

terraform_build:
  stage: set_up_infrastructure
  before_script:
    - apt-get update -y && apt-get install awscli ansible docker.io python3-pip -y
    - cp $SSH_PRIVATE_KEY ./us-east-1-key.pem
  script:
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
  artifacts:
    paths:
      - inventory

build_image:
  stage: build_image
  before_script:
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 373000727222.dkr.ecr.us-east-1.amazonaws.com
  script:
    - docker build -t 373000727222.dkr.ecr.us-east-1.amazonaws.com/webapp:website-1.0 .
    - docker push 373000727222.dkr.ecr.us-east-1.amazonaws.com/webapp:website-1.0

deploy:
  stage: deploy
  script:
    - ansible-playbook --private-key $SSH_PRIVATE_KEY playbook.yml