stages:
  - build_image

build_image:
  stage: build_image
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - apk update -y && apk add awscli
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 373000727222.dkr.ecr.us-east-1.amazonaws.com
  script:
    - docker build -t 373000727222.dkr.ecr.us-east-1.amazonaws.com/webapp:website-1.0 .
    - docker push 373000727222.dkr.ecr.us-east-1.amazonaws.com/webapp:website-1.0