stages:
  - set_up_infrastructure
  - build_image
  - deploy

terraform_build:
  stage: set_up_infrastructure
  image: ubuntu:20.04
  before_script:
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    - apt update && apt install terraform
    - terraform init
  script:
    - terraform plan
    - terraform apply -auto-approve
  artifacts:
    paths:
      - inventory
  
build_image:
  stage: build_image
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - apt-get update -y && apt-get install awscli
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 373000727222.dkr.ecr.us-east-1.amazonaws.com
  script:
    - docker build -t 373000727222.dkr.ecr.us-east-1.amazonaws.com/webapp:website-1.0 .
    - docker push 373000727222.dkr.ecr.us-east-1.amazonaws.com/webapp:website-1.0

deploy:
  stage: deploy
  image: ubuntu:20.04
  before_script:
    - pip install docker
  script:
    - ansible-playbook --private-key $SSH_PRIVATE_KEY playbook.yml