---
- name: install packages
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Ensure packages are installed
    apt:
      update_cache: yes
      pkg:
      - awscli
      - docker.io
      state: present
